**DATE-TIME NULL HANDLING**

In [ ]:
import pandas as pd
df = pd.read_csv('/content/sample_data/shirpurGoldRefinery.csv')
df

,Date,Open Price,High Price,Low Price,Close Price,WAP,No.of Shares,No. of Trades,Total Turnover (Rs.),Deliverable Quantity,% Deli. Qty to Traded Qty,Spread High-Low,Spread Close-Open
0,29-December-2017,203.55,206.5,201.00,201.85,202.760380,3372,68,683708.0,2202,65.30,5.50,-1.70
1,28-December-2017,202.00,207.6,199.55,202.80,203.118439,8612,196,1749256.0,5063,58.79,8.05,0.80
2,27-December-2017,209.10,213.6,195.20,197.80,202.801825,24983,426,5066598.0,14168,56.71,18.40,-11.30
3,26-December-2017,216.50,219.9,207.20,209.70,213.418007,17782,363,3794999.0,7540,42.40,12.70,-6.80
4,22-December-2017,218.95,233.6,212.40,218.15,223.089049,165976,2710,37027428.0,60121,36.22,21.20,-0.80
...,...,...,...,...,...,...,...,...,...,...,...,...,...
243,6-January-2017,110.10,110.1,107.80,110.10,110.048719,2771,34,304945.0,2045,73.80,2.30,0.00
244,5-January-2017,101.00,104.9,100.00,104.90,103.352347,9993,147,1032800.0,5969,59.73,4.90,3.90
245,4-January-2017,99.50,102.0,99.50,99.95,100.293226,4488,101,450116.0,3422,76.25,2.50,0.45
246,3-January-2017,102.00,102.0,100.05,100.65,100.784909,6295,101,634441.0,4205,66.80,1.95,-1.35
247,2-January-2017,104.00,104.0,99.00,101.65,101.302024,5483,182,555439.0,5062,92.32,5.00,-2.35

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 248 entries, 0 to 247
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Date                       248 non-null    object
 1   Open Price                 248 non-null    float64
 2   High Price                 248 non-null    float64
 3   Low Price                  248 non-null    float64
 4   Close Price                248 non-null    float64
 5   WAP                        248 non-null    float64
 6   No.of Shares               248 non-null    int64
 7   No. of Trades              248 non-null    int64
 8   Total Turnover (Rs.)       248 non-null    float64
 9   Deliverable Quantity       248 non-null    int64
 10  % Deli. Qty to Traded Qty  248 non-null    float64
 11  Spread High-Low            248 non-null    float64
 12  Spread Close-Open          248 non-null    float64
dtypes: float64(9), int64(3), object(1)
memory usage: 25.3+ KB

In [ ]:
df['Date'].max()

'9-October-2017'

## **COVERTING METHODS**   --  Dtype

In [ ]:
df['Timestamp'] = pd.to_datetime(df['Date'])
df

,Date,Open Price,High Price,Low Price,Close Price,WAP,No.of Shares,No. of Trades,Total Turnover (Rs.),Deliverable Quantity,% Deli. Qty to Traded Qty,Spread High-Low,Spread Close-Open,Timestamp
0,29-December-2017,203.55,206.5,201.00,201.85,202.760380,3372,68,683708.0,2202,65.30,5.50,-1.70,2017-12-29
1,28-December-2017,202.00,207.6,199.55,202.80,203.118439,8612,196,1749256.0,5063,58.79,8.05,0.80,2017-12-28
2,27-December-2017,209.10,213.6,195.20,197.80,202.801825,24983,426,5066598.0,14168,56.71,18.40,-11.30,2017-12-27
3,26-December-2017,216.50,219.9,207.20,209.70,213.418007,17782,363,3794999.0,7540,42.40,12.70,-6.80,2017-12-26
4,22-December-2017,218.95,233.6,212.40,218.15,223.089049,165976,2710,37027428.0,60121,36.22,21.20,-0.80,2017-12-22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
243,6-January-2017,110.10,110.1,107.80,110.10,110.048719,2771,34,304945.0,2045,73.80,2.30,0.00,2017-01-06
244,5-January-2017,101.00,104.9,100.00,104.90,103.352347,9993,147,1032800.0,5969,59.73,4.90,3.90,2017-01-05
245,4-January-2017,99.50,102.0,99.50,99.95,100.293226,4488,101,450116.0,3422,76.25,2.50,0.45,2017-01-04
246,3-January-2017,102.00,102.0,100.05,100.65,100.784909,6295,101,634441.0,4205,66.80,1.95,-1.35,2017-01-03
247,2-January-2017,104.00,104.0,99.00,101.65,101.302024,5483,182,555439.0,5062,92.32,5.00,-2.35,2017-01-02

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 248 entries, 0 to 247
Data columns (total 14 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Date                       248 non-null    object
 1   Open Price                 248 non-null    float64
 2   High Price                 248 non-null    float64
 3   Low Price                  248 non-null    float64
 4   Close Price                248 non-null    float64
 5   WAP                        248 non-null    float64
 6   No.of Shares               248 non-null    int64
 7   No. of Trades              248 non-null    int64
 8   Total Turnover (Rs.)       248 non-null    float64
 9   Deliverable Quantity       248 non-null    int64
 10  % Deli. Qty to Traded Qty  248 non-null    float64
 11  Spread High-Low            248 non-null    float64
 12  Spread Close-Open          248 non-null    float64
 13  Timestamp                  248 non-null    datetime64[ns]
dtypes: datetime64[ns](1), float64(9), int64(3), object(1)
memory usage: 27.2+ KB

In [ ]:
df['Timestamp'].max()

Timestamp('2017-12-29 00:00:00')

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
data = "2024/jan/31"

In [ ]:
import pandas as pd

In [ ]:
datetime=pd.to_datetime(data,format='%Y/%b/%d')

In [ ]:
type(datetime)

pandas._libs.tslibs.timestamps.Timestamp

#how to convert to timestamp

* %a weekdays as locales abbreviated name sun,mon
* %A weekdays as locales full name. sunday,monday
* %w weekdays as a decimal number monday:0,sunday:6
* %a weekday as locales abbreviated name sun,mon
* %d Day of month as a zero padded decimal number.01,02
* %b month as locales abbreviated name. jan,feb, dec
* %B month as locales full name. january
* %y year without centuary. 2000 as 00
* %Y year with centuary as a decimal number. 2013
* %H hour (24 hour clock). 00,01,...,23
* %I hour(12 hour clock). 00,01,...,12
* %M minute as zero padded decimal number.00,01,...,59
* %S second as a zero padded decimal number. 00,01,...,59

In [ ]:
data = ["2024/jan/31",'2024/march/12']

In [3]:
import pandas as pd

In [4]:
datetime=pd.to_datetime(data)

In [5]:
type(datetime)

pandas._libs.tslibs.timestamps.Timestamp

In [6]:
datetime

Timestamp('2024-01-01 10:05:45')

* to get day from the datetime

In [7]:
from datetime import date
data = "2024-jan-01 10:05:45"
datetime =pd.to_datetime(data)
datetime = pd.to_datetime(data)
print(datetime)

print(datetime.day)

print(datetime.day_of_week)

print(datetime.day_name())

print(datetime.day_of_year)

print(datetime.days_in_month)

print(datetime.is_leap_year)

print(datetime.is_month_end)

print(datetime.is_month_start)

print(datetime.is_quarter_end)

print(datetime.is_quarter_start)

print(datetime.is_year_end)

print(datetime.is_year_start)

print(datetime.month)

print(datetime.month_name())

print(datetime.quarter)

print(datetime.week)

print(datetime.weekofyear)

print(datetime.year)

print(datetime.hour)

print(datetime.minute)

print(datetime.second)

print(datetime.microsecond)

2024-01-01 10:05:45
1
0
Monday
1
31
True
False
True
False
True
False
True
1
January
1
1
1
2024
10
5
45
0

In [8]:
df=pd.read_csv('/shirpurGoldRefinery.csv')
df.info()

FileNotFoundError: [Errno 2] No such file or directory: '/shirpurGoldRefinery.csv'

In [9]:
df['Timestamp']=pd.to_datetime(df['Date'])
df.info()

NameError: name 'df' is not defined

In [ ]:
df['year']=df['Timestamp'].dt.year
df['month']=df['Timestamp'].dt.month
df['day']=df['Timestamp'].dt.day
df['month_name']=df['Timestamp'].dt.month_name()
df['dayofweek']=df['Timestamp'].dt.dayofweek
df['day_name']=df['Timestamp'].dt.day_name()
df['dayofyear']=df['Timestamp'].dt.dayofyear
df['hour']=df['Timestamp'].dt.hour
df['minute']=df['Timestamp'].dt.minute

In [10]:
df.info()

NameError: name 'df' is not defined

In [ ]:
df.head()

,Date,Open Price,High Price,Low Price,Close Price,WAP,No.of Shares,No. of Trades,Total Turnover (Rs.),Deliverable Quantity,...,Timestamp,year,month,day,month_name,dayofweek,day_name,dayofyear,hour,minute
0,29-December-2017,203.55,206.5,201.00,201.85,202.760380,3372,68,683708.0,2202,...,2017-12-29,2017,12,29,December,4,Friday,363,0,0
1,28-December-2017,202.00,207.6,199.55,202.80,203.118439,8612,196,1749256.0,5063,...,2017-12-28,2017,12,28,December,3,Thursday,362,0,0
2,27-December-2017,209.10,213.6,195.20,197.80,202.801825,24983,426,5066598.0,14168,...,2017-12-27,2017,12,27,December,2,Wednesday,361,0,0
3,26-December-2017,216.50,219.9,207.20,209.70,213.418007,17782,363,3794999.0,7540,...,2017-12-26,2017,12,26,December,1,Tuesday,360,0,0
4,22-December-2017,218.95,233.6,212.40,218.15,223.089049,165976,2710,37027428.0,60121,...,2017-12-22,2017,12,22,December,4,Friday,356,0,0

In [ ]:
df['day']=pd.DatetimeIndex(df['Date']).day
df['month']=pd.DatetimeIndex(df['Date']).month
df['year']=pd.DatetimeIndex(df['Date']).year

In [ ]:
df.head()

,Date,Open Price,High Price,Low Price,Close Price,WAP,No.of Shares,No. of Trades,Total Turnover (Rs.),Deliverable Quantity,...,Timestamp,year,month,day,month_name,dayofweek,day_name,dayofyear,hour,minute
0,2017-12-29,203.55,206.5,201.00,201.85,202.760380,3372,68,683708.0,2202,...,2017-12-29,2017,12,29,December,4,Friday,363,0,0
1,2017-12-28,202.00,207.6,199.55,202.80,203.118439,8612,196,1749256.0,5063,...,2017-12-28,2017,12,28,December,3,Thursday,362,0,0
2,2017-12-27,209.10,213.6,195.20,197.80,202.801825,24983,426,5066598.0,14168,...,2017-12-27,2017,12,27,December,2,Wednesday,361,0,0
3,2017-12-26,216.50,219.9,207.20,209.70,213.418007,17782,363,3794999.0,7540,...,2017-12-26,2017,12,26,December,1,Tuesday,360,0,0
4,2017-12-22,218.95,233.6,212.40,218.15,223.089049,165976,2710,37027428.0,60121,...,2017-12-22,2017,12,22,December,4,Friday,356,0,0

In [2]:
df.drop_duplicates(inplace=True)

NameError: name 'df' is not defined

In [1]:
from datetime import date
data = "2024-jan-01 10:05:45"
datetime =pd.to_datetime(data)
datetime = pd.to_datetime(data)
print(datetime)

print(datetime.day)

print(datetime.day_of_week)

print(datetime.day_name())

print(datetime.day_of_year)

print(datetime.days_in_month)

print(datetime.is_leap_year)

print(datetime.is_month_end)

print(datetime.is_month_start)

print(datetime.is_quarter_end)

print(datetime.is_quarter_start)

print(datetime.is_year_end)

print(datetime.is_year_start)

print(datetime.month)

print(datetime.month_name())

print(datetime.quarter)

print(datetime.week)

print(datetime.weekofyear)

print(datetime.year)

print(datetime.hour)

print(datetime.minute)

print(datetime.second)

print(datetime.microsecond)

NameError: name 'pd' is not defined

In [11]:
df = df.drop('Date', axis=1)

NameError: name 'df' is not defined

In [12]:
cor_metrix = df.corr()['No. of Trades']
cor_metrix

NameError: name 'df' is not defined